-- Таблицы для базы данных по кредитным рискам

-- Удаление структуры
-- DROP TABLE [IF EXISTS] table_name [CASCADE | RESTRICT];
drop table if exists guarantee_limits cascade;
drop table if exists guarantee_names cascade;
drop table if exists guarantee_reports cascade;
drop table if exists guarantee_approval_docs cascade;
drop table if exists guarantee_approval_doc_types cascade;
drop table if exists guarantees cascade;
drop table if exists guarantee_types cascade;
drop table if exists subsidiaries cascade;
drop table if exists counterparty_portfolios cascade;
drop table if exists portfolios cascade;
drop table if exists committees cascade;
drop table if exists committee_statuses cascade;
drop table if exists committee_limits cascade;
drop table if exists rating_internals cascade;
drop table if exists financial_statements cascade;
drop table if exists financial_statement_standards cascade;
drop table if exists rating_externals cascade;
drop table if exists counterparties cascade;
drop table if exists counterparty_groups cascade;
drop table if exists financial_sectors cascade;
drop table if exists rating_countries cascade;
drop table if exists countries cascade;
drop table if exists ratings cascade;
drop table if exists rating_groups cascade;
drop table if exists rating_agencies cascade;
drop table if exists risk_classes cascade;
drop table if exists currency_rates cascade;
drop table if exists currencies cascade;
drop table if exists user_settings cascade;

-- Таблица дочерних компаний
CREATE TABLE subsidiaries (
	id int primary key generated by default as identity,
	code int NOT NULL UNIQUE,
	name varchar(255) NOT NULL UNIQUE
);
-- Таблица портфелей
CREATE TABLE portfolios (
	id int primary key generated by default as identity,
	name varchar(50) not null
);
-- Таблица секторов экономики
CREATE TABLE financial_sectors (
	id int primary key generated by default as identity,
	name varchar(50) not null unique,
	name_ru varchar(50) not null unique
);
-- Таблица стран
CREATE TABLE countries (
	id int primary key generated by default as identity,
	name varchar(100) not null unique,
	name_ru varchar(100) not null unique,
	short_name varchar(2) not null unique,
	ticker varchar(50) null
);
-- Таблица групп комитетов
create table counterparty_groups (
	id int primary key generated by default as identity,
	name varchar(20) not null unique
);
-- Таблица контрагентов-банков (или дополнительные поля)
--CREATE TABLE CounterpartyAddons (
--	Id int not null identity(1,1) primary key,
--	Swift nvarchar(50) null,
--	Inn nvarchar(20) null,
--	Ticket nvarchar(20) null
--)
-- Таблица контрагентов
CREATE TABLE counterparties (
	id int primary key generated by default as identity,
	name varchar(450) not null unique,
	short_name varchar(15) not null unique,
	intra_group boolean not null default false,
	date_start date not null,
	comment varchar(1000) null,
	monitored boolean not null default false,
	ticker varchar(50) null,
	inn varchar(30) null,
	swift varchar(100) null,
	bank_class varchar null,
	financial_sector_id int,
	country_id int,
	country_risk_id int,
	rating_donor_id int,
	counterparty_group_id int,
	gtc varchar(10) null,
	long_term boolean not null default false,
	etp boolean not null default false,
	efet boolean not null default false,
	constraint counterparty_financial_sector_id_fkey foreign key (financial_sector_id)
	    references financial_sectors(id) match simple
	    on update no action on delete no action,
	constraint counterparty_country_id_fkey foreign key (country_id)
	    references countries(id) match simple
	    on update no action on delete no action,
	constraint counterparty_country_risk_id_fkey foreign key (country_risk_id)
	    references countries(id) match simple
	    on update no action on delete no action,
	constraint counterparty_rating_donor_id_fkey foreign key (rating_donor_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint counterparty_counterparty_group_id_fkey foreign key (counterparty_group_id)
	    references counterparty_groups(id) match simple
	    on update no action on delete no action
);
-- Таблица контрагент-портфель
CREATE TABLE counterparty_portfolios (
	counterparty_id int not null,
	portfolio_id int not null,
	primary key (counterparty_id, portfolio_id),
	constraint counterparty_portfolios_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint counterparty_portfolios_portfolio_id_fkey foreign key (portfolio_id)
	    references portfolios(id) match simple
	    on update no action on delete no action
);
-- Таблица статусов комитетов
create table committee_statuses (
	id int primary key generated by default as identity,
	name varchar(100) not null unique
);
-- Таблица ограничений комитетов
create table committee_limits (
	id int primary key generated by default as identity,
	name varchar(100) not null unique
);
-- Таблица комитетов
create table committees (
	id int primary key generated by default as identity,
	counterparty_id int,
	committee_status_id int,
	committee_limit_id int,
	date_start date not null,
	comment varchar(1000) null,
	constraint committees_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
    constraint committees_committee_status_id_fkey foreign key (committee_status_id)
	    references committee_statuses(id) match simple
	    on update no action on delete no action,
    constraint committees_committee_limit_id_fkey foreign key (committee_limit_id)
	    references committee_limits(id) match simple
	    on update no action on delete no action
);
-- Группы рейтингов
create table rating_groups (
	id int primary key generated by default as identity,
	g_number int not null unique,
	g_limit bigint,
	g_limit_bank bigint
);
-- Таблица значений рейтингов
create table ratings (
	id int primary key generated by default as identity,
	score int not null unique,
	name varchar(6) not null unique,
	rating_group_id int,
	constraint ratings_rating_group_id_fkey foreign key (rating_group_id)
	    references rating_groups(id) match simple
	    on update no action on delete no action
);
-- Рейтинговые агенства
create table rating_agencies (
	id int primary key generated by default as identity,
	name varchar(30) not null unique
);
-- Рейтинги стран
create table rating_countries (
	id int primary key generated by default as identity,
	date_start date not null,
	rating_agency_id int,
	rating_id int,
	country_id int,
	constraint rating_countries_rating_agency_id_fkey foreign key (rating_agency_id)
	    references rating_agencies(id) match simple
	    on update no action on delete no action,
	constraint rating_countries_rating_id_fkey foreign key (rating_id)
	    references ratings(id) match simple
	    on update no action on delete no action,
	constraint rating_countries_country_id_fkey foreign key (country_id)
	    references countries(id) match simple
	    on update no action on delete no action
);
-- Класс риска
create table risk_classes (
	id int primary key generated by default as identity,
	name varchar(10) not null unique
);
-- Виды валют
create table currencies (
	id int primary key generated by default as identity,
	name varchar(3) not null unique
);
-- Курсы валют на дату
create table currency_rates (
	id int primary key generated by default as identity,
	currency_from_id int,
	currency_to_id int,
	rate float not null,
	date_report date not null,
	unique (currency_from_id, currency_to_id, date_report),
	constraint currency_rates_currency_from_id_fkey foreign key (currency_from_id)
	    references currencies(id) match simple
	    on update no action on delete no action,
	constraint currency_rates_currency_to_id_fkey foreign key (currency_to_id)
	    references currencies(id) match simple
	    on update no action on delete no action
);
-- Внешний рейтинг контрагентов
create table rating_externals (
	id int primary key generated by default as identity,
	date_start date not null,
	counterparty_id int,
	rating_agency_id int,
	rating_id int,
	unique (date_start, counterparty_id, rating_agency_id),
	constraint rating_externals_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint rating_externals_rating_agency_id_fkey foreign key (rating_agency_id)
	    references rating_agencies(id) match simple
	    on update no action on delete no action,
	constraint rating_externals_rating_id_fkey foreign key (rating_id)
	    references ratings(id) match simple
	    on update no action on delete no action
);
-- Финансовые условия - стандарты
create table financial_statement_standards (
	id int primary key generated by default as identity,
	name varchar(100) not null unique
);
-- Финансовые условия
create table financial_statements (
	id int primary key generated by default as identity,
	date_start date not null,
	comment varchar(1000),
	counterparty_id int,
	standard_id int,
	constraint financial_statements_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint financial_statements_standard_id_fkey foreign key (standard_id)
	    references financial_statement_standards(id) match simple
	    on update no action on delete no action
);
-- Внутренний рейтинг контрагентов
create table rating_internals (
	id int primary key generated by default as identity,
	date_start date not null,
	conservative boolean default false,
	analyst varchar(30) not null,
	comment varchar(1000) null,
	counterparty_id int not null,
	rating_id int not null,
	rating_wc_id int,
	risk_class_id int,
	financial_statement_id int,
    constraint rating_internals_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint rating_internals_rating_id_fkey foreign key (rating_id)
	    references ratings(id) match simple
	    on update no action on delete no action,
	constraint rating_internals_rating_wc_id_fkey foreign key (rating_wc_id)
	    references ratings(id) match simple
	    on update no action on delete no action,
	constraint rating_internals_risk_class_id_fkey foreign key (risk_class_id)
	    references risk_classes(id) match simple
	    on update no action on delete no action,
	constraint rating_internals_financial_statement_id_fkey foreign key (financial_statement_id)
	    references financial_statements(id) match simple
	    on update no action on delete no action
);
-- ГАРАНТИИ
-- Виды гарантий
create table guarantee_types (
	id int primary key generated by default as identity,
	name varchar(100) not null unique
);
-- Гарантии
create table guarantees (
	id int primary key generated by default as identity,
	number varchar(100) null,
	date_start date not null,
	amount_initial bigint null,
	currency_id int,
	counterparty_id int,
	guarantor_id int,
	guarantee_type_id int,
	beneficiar_id int,
	subsidiary_id int,
	comment varchar(1000) null,
	constraint guarantees_currency_id_fkey foreign key (currency_id)
	    references currencies(id) match simple
	    on update no action on delete no action,
	constraint guarantees_counterparty_id_fkey foreign key (counterparty_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint guarantees_guarantor_id_fkey foreign key (guarantor_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint guarantees_guarantee_type_id_fkey foreign key (guarantee_type_id)
	    references guarantee_types(id) match simple
	    on update no action on delete no action,
	constraint guarantees_beneficiar_id_fkey foreign key (beneficiar_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint guarantees_subsidiary_id_fkey foreign key (subsidiary_id)
	    references subsidiaries(id) match simple
	    on update no action on delete no action
);
-- Суммы гарантий на дату
create table guarantee_reports (
	id int primary key generated by default as identity,
	guarantee_id int,
	date_report date not null,
	date_expiration date null,
	amount_start bigint not null,
	amount_end bigint not null,
	amount_operation bigint null,
	constraint guarantee_reports_guarantee_id_fkey foreign key (guarantee_id)
	    references guarantees(id) match simple
	    on update no action on delete no action
);
-- Лимиты на гарантии
create table guarantee_limits (
	id int primary key generated by default as identity,
	guarantor_id int,
	date_agree_start date not null,
	date_agree_end date not null,
	date_end date not null,
	amount bigint null,
	currency_id int,
	guarantee_type_id int,
	constraint guarantee_limits_guarantor_id_fkey foreign key (guarantor_id)
	    references counterparties(id) match simple
	    on update no action on delete no action,
	constraint guarantee_limits_currency_id_fkey foreign key (currency_id)
	    references currencies(id) match simple
	    on update no action on delete no action,
	constraint guarantee_limits_guarantee_type_id_fkey foreign key (guarantee_type_id)
	    references guarantee_types(id) match simple
	    on update no action on delete no action
);
-- Виды подтверждающих документов на гарантии
create table guarantee_approval_doc_types (
	id int primary key generated by default as identity,
	name varchar(255) not null unique
);
-- Подтверждающие документы на гарантии
create table guarantee_approval_docs (
	id int primary key generated by default as identity,
	guarantee_id int,
	date_approval date not null,
	guarantee_approval_doc_type_id int,
	number varchar(1000) not null,
	constraint guarantee_approval_docs_guarantee_id_fkey foreign key (guarantee_id)
	    references guarantees(id) match simple
	    on update no action on delete no action,
	constraint guarantee_approval_docs_guarantee_approval_doc_type_id_fkey foreign key (guarantee_approval_doc_type_id)
	    references guarantee_approval_doc_types(id) match simple
	    on update no action on delete no action
);
create table user_settings (
	id int primary key generated by default as identity,
	username varchar(255) not null,
	table_counterparty_show_id boolean,
	table_counterparty_show_short_name boolean,
	table_counterparty_show_sector boolean,
	table_counterparty_show_country_of_risk boolean,
	table_counterparty_show_country_of_domicile boolean,
	table_counterparty_show_intra_group boolean,
	table_counterparty_show_portfolio boolean,
	table_counterparty_show_donor boolean,
	table_counterparty_show_start_date boolean,
	table_counterparty_show_comment boolean,
	table_counterparty_show_inn boolean,
	table_counterparty_show_swift boolean,
	table_counterparty_show_ticker boolean,
	table_counterparty_show_last_int_rating boolean,
	table_counterparty_show_last_ext_rating boolean,
	table_counterparty_show_active_rating boolean,
	table_counterparty_show_effective_rating boolean
)
